// Trains the note reader's head from the labelled corpus and writes src/data/feelingHead.json.
//
//   npm run train:head                       train on every labelled set, write the head
//   npm run train:head -- --cv               first print 5-fold cross-validation for a few lambdas
//   npm run train:head -- --lambda 0.3       choose the regularisation yourself
//   npm run train:head -- --sets dev,dev2    train on only these sets (files in tests/corpus/)
//
// Needs the model (`npm run model`). Everything here is deterministic: the same notes and the same
// model always give the same head.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createNodeEmbedder } from './embedder.mjs'
import { crossValidatedProbs, train } from './lr.mjs'
import { acceptedFeelings, describe, rankIds, scoreRanked } from './metrics.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`)
  return i === -1 ? fallback : (process.argv[i + 1] ?? fallback)
}

// Every labelled set. fresh4 and fresh5 were held out and scored once before being added here.
// A set the head is trained on can no longer measure it honestly: use `npm run evaluate:model`
// with a file the head has NOT seen (your own real notes) for that.
const DEFAULT_SETS = ['dev', 'dev2', 'dev3', 'dev4', 'fresh4', 'fresh5']
const sets = arg('sets', DEFAULT_SETS.join(',')).split(',')
const lambda = Number(arg('lambda', 0.3))
const feelingIds = Object.keys(
  JSON.parse(readFileSync(join(root, 'src/data/feelings.json'), 'utf8')).feelings,
)

const notes = []
for (const set of sets) {
  const file = JSON.parse(readFileSync(join(root, 'tests/corpus', `${set}.json`), 'utf8'))
  for (const row of file.notes) notes.push(row)
}
console.log(`${notes.length} notes from ${sets.join(', ')}`)

const embedder = await createNodeEmbedder()
const vectors = await embedder.embedAll(notes.map((n) => n[0]))

// soft targets: a note that accepts several feelings is trained towards all of them equally
const rows = []
const rowNotes = []
notes.forEach((note, i) => {
  const accepted = acceptedFeelings(note[1])
  if (accepted === null) return
  const y = new Array(feelingIds.length).fill(0)
  for (const f of accepted) y[feelingIds.indexOf(f)] += 1 / accepted.length
  rows.push({ x: vectors[i], y })
  rowNotes.push(note)
})
console.log(`${rows.length} usable notes (notes that accept any feeling are skipped)`)

if (process.argv.includes('--cv')) {
  console.log('\n5-fold cross-validation (each note predicted by a model that never saw it):')
  for (const l of [0.1, 0.3, 1]) {
    const probs = crossValidatedProbs(rows, { lambda: l })
    console.log(
      `  lambda ${String(l).padEnd(3)}  ${describe(scoreRanked(rowNotes, (i) => rankIds(probs[i], feelingIds)))}`,
    )
  }
}

const model = train(rows, { lambda })
const round = (v) => Math.round(v * 1e5) / 1e5
const head = {
  about:
    'Generated by `npm run train:head` from the labelled notes in tests/corpus/. Do not edit by hand: change the notes or the model, then train again.',
  model: {
    id: embedder.manifest.id,
    revision: embedder.manifest.source.revision,
    dtype: embedder.manifest.dtype,
    // total download, so the app can show honest progress (the browser cannot always tell)
    bytes: embedder.manifest.files.reduce((sum, f) => sum + f.bytes, 0),
    prefix: embedder.manifest.prefix,
    pooling: embedder.manifest.pooling,
  },
  feelings: feelingIds,
  lambda,
  trainedOn: { notes: rows.length, sets },
  dim: model.mean.length,
  mean: model.mean.map(round),
  sd: model.sd.map(round),
  W: model.W.map((w) => w.map(round)),
  b: model.b.map(round),
}
// one row of numbers per line, so a retrain shows up as a readable diff
const NL = String.fromCharCode(10)
function compact(value, indent = '') {
  if (Array.isArray(value) && value.every((v) => typeof v !== 'object'))
    return JSON.stringify(value)
  const inner = `${indent} `
  if (Array.isArray(value)) {
    return ['[', value.map((v) => inner + compact(v, inner)).join(`,${NL}`), `${indent}]`].join(NL)
  }
  if (value && typeof value === 'object') {
    const lines = Object.entries(value).map(
      ([k, v]) => `${inner}${JSON.stringify(k)}: ${compact(v, inner)}`,
    )
    return ['{', lines.join(`,${NL}`), `${indent}}`].join(NL)
  }
  return JSON.stringify(value)
}
const body = compact(head)
writeFileSync(join(root, 'src/data/feelingHead.json'), `${body}\n`)
console.log(
  `\nwrote src/data/feelingHead.json (lambda ${lambda}, ${head.dim} dimensions, ${(body.length / 1024).toFixed(0)} KB)`,
)
